# Generated by Django 3.1 on 2020-08-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1500, verbose_name='Ссылка на статью')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст статьи')),
                ('status', models.SmallIntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILED')], verbose_name='Статус')),
                ('err_message', models.CharField(blank=True, max_length=300, null=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'articles',
            },
        ),
    ]
