FROM python:3.8
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y --no-install-recommends \
     gcc \
     python-pip \
     tzdata \
     locales \
     git-core \
     libvips42

RUN mkdir /code
WORKDIR /code

ADD requirements.txt /code/
RUN pip install -IUr requirements.txt
ADD . /code/

RUN chmod +x run_celery.sh

